export const products = [
    {"id":1,"imgUrl": "../../../assets/images/product.jpg","product":"Bag","supplierId":1,"categoryId":1,"unit":"10 boxes x 20 bags","price":18},
    {"id":2,"imgUrl": "../../../assets/images/product.jpg","product":"Bottle","supplierId":1,"categoryId":1,"unit":"24 - 12 oz bottles","price":19},
    {"id":3,"imgUrl": "../../../assets/images/product.jpg","product":"Cough Syrup","supplierId":1,"categoryId":2,"unit":"12 - 550 ml bottles","price":10},
    {"id":4,"imgUrl": "../../../assets/images/product.jpg","product":"Jar","supplierId":2,"categoryId":2,"unit":"48 - 6 oz jars","price":22},
    {"id":5,"imgUrl": "../../../assets/images/product.jpg","product":"Jar Mix","supplierId":2,"categoryId":2,"unit":"36 boxes","price":21.35},
    {"id":6,"imgUrl": "../../../assets/images/product.jpg","product":"Advanced Jar","supplierId":3,"categoryId":2,"unit":"12 - 8 oz jars","price":25},
    {"id":7,"imgUrl": "../../../assets/images/product.jpg","product":"Medimics","supplierId":3,"categoryId":7,"unit":"12 - 1 lb pkgs.","price":30},
    {"id":8,"imgUrl": "../../../assets/images/product.jpg","product":"Strwaberry Jar","supplierId":3,"categoryId":2,"unit":"12 - 12 oz jars","price":40},
    {"id":9,"imgUrl": "../../../assets/images/product.jpg","product":"Mishi Kobe Niku","supplierId":4,"categoryId":6,"unit":"18 - 500 g pkgs.","price":97},
    {"id":10,"imgUrl": "../../../assets/images/product.jpg","product":"Ikura","supplierId":4,"categoryId":8,"unit":"12 - 200 ml jars","price":31},
    {"id":11,"imgUrl": "../../../assets/images/product.jpg","product":"Queso Cabrales","supplierId":5,"categoryId":4,"unit":"1 kg pkg.","price":21},
    {"id":12,"imgUrl": "../../../assets/images/product.jpg","product":"Queso Manchego La Pastora","supplierId":5,"categoryId":4,"unit":"10 - 500 g pkgs.","price":38},
    {"id":14,"imgUrl": "../../../assets/images/product.jpg","product":"Tofu","supplierId":6,"categoryId":7,"unit":"40 - 100 g pkgs.","price":23.25},
    {"id":15,"imgUrl": "../../../assets/images/product.jpg","product":"Genen Shouyu","supplierId":6,"categoryId":2,"unit":"24 - 250 ml bottles","price":15.5},
    {"id":16,"imgUrl": "../../../assets/images/product.jpg","product":"Pavlova","supplierId":7,"categoryId":3,"unit":"32 - 500 g boxes","price":17.45},
    {"id":17,"imgUrl": "../../../assets/images/product.jpg","product":"Alice Mutton","supplierId":7,"categoryId":6,"unit":"20 - 1 kg tins","price":39},
    {"id":18,"imgUrl": "../../../assets/images/product.jpg","product":"Carnarvon Tigers","supplierId":7,"categoryId":8,"unit":"16 kg pkg.","price":62.5},
    {"id":20,"imgUrl": "../../../assets/images/product.jpg","product":"Sir Rodney's Marmalade","supplierId":8,"categoryId":3,"unit":"30 gift boxes","price":81}
]